-- Generic competition location structure for state/subdivision selection.
-- Additive and idempotent: Michigan is the first enabled beta state, but the
-- schema supports districts, regions, areas, and future annual conferences.

create table if not exists public.states (
  id bigint generated by default as identity primary key,
  code text not null unique check (code = upper(code) and length(code) = 2),
  name text not null,
  is_active boolean not null default false,
  subdivision_type text not null default 'district',
  subdivision_label text not null default 'District',
  subdivision_label_plural text not null default 'Districts',
  district_selection_enabled boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.deca_subdivisions (
  id text primary key,
  state_code text not null references public.states(code) on update cascade on delete restrict,
  type text not null check (type in ('district', 'region', 'area')),
  number integer not null check (number > 0),
  name text not null,
  display_name text not null,
  is_active boolean not null default true,
  season text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (state_code, type, number, season)
);

create table if not exists public.deca_conferences (
  id text primary key,
  season text not null,
  level text not null check (level in ('district', 'region', 'area', 'state', 'international')),
  state_code text not null references public.states(code) on update cascade on delete restrict,
  subdivision_id text references public.deca_subdivisions(id) on update cascade on delete set null,
  name text not null,
  start_date date,
  end_date date,
  venue text,
  city text,
  status text not null default 'tba' check (status in ('confirmed', 'tba', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles add column if not exists state_code text;
alter table public.profiles add column if not exists deca_subdivision_id text;
alter table public.profiles add column if not exists subdivision_status text not null default 'unknown';

alter table public.profiles drop constraint if exists profiles_state_code_fkey;
alter table public.profiles add constraint profiles_state_code_fkey
  foreign key (state_code) references public.states(code) on update cascade on delete set null;

alter table public.profiles drop constraint if exists profiles_deca_subdivision_id_fkey;
alter table public.profiles add constraint profiles_deca_subdivision_id_fkey
  foreign key (deca_subdivision_id) references public.deca_subdivisions(id) on update cascade on delete set null;

alter table public.profiles drop constraint if exists profiles_subdivision_status_check;
alter table public.profiles add constraint profiles_subdivision_status_check
  check (subdivision_status in ('user_selected', 'auto_detected', 'unknown'));

insert into public.states (
  code, name, is_active, subdivision_type, subdivision_label,
  subdivision_label_plural, district_selection_enabled
) values (
  'MI', 'Michigan', true, 'district', 'District', 'Districts', true
) on conflict (code) do update set
  name = excluded.name,
  is_active = excluded.is_active,
  subdivision_type = excluded.subdivision_type,
  subdivision_label = excluded.subdivision_label,
  subdivision_label_plural = excluded.subdivision_label_plural,
  district_selection_enabled = excluded.district_selection_enabled,
  updated_at = now();

insert into public.deca_subdivisions (
  id, state_code, type, number, name, display_name, is_active, season
) values
  ('MI-D1', 'MI', 'district', 1, 'District 1', 'District 1', true, '2026-27'),
  ('MI-D2', 'MI', 'district', 2, 'District 2', 'District 2', true, '2026-27'),
  ('MI-D3', 'MI', 'district', 3, 'District 3', 'District 3', true, '2026-27'),
  ('MI-D4', 'MI', 'district', 4, 'District 4', 'District 4', true, '2026-27'),
  ('MI-D5', 'MI', 'district', 5, 'District 5', 'District 5', true, '2026-27'),
  ('MI-D6', 'MI', 'district', 6, 'District 6', 'District 6', true, '2026-27'),
  ('MI-D7', 'MI', 'district', 7, 'District 7', 'District 7', true, '2026-27'),
  ('MI-D8', 'MI', 'district', 8, 'District 8', 'District 8', true, '2026-27'),
  ('MI-D9', 'MI', 'district', 9, 'District 9', 'District 9', true, '2026-27')
on conflict (id) do update set
  state_code = excluded.state_code,
  type = excluded.type,
  number = excluded.number,
  name = excluded.name,
  display_name = excluded.display_name,
  is_active = excluded.is_active,
  season = excluded.season,
  updated_at = now();

insert into public.deca_conferences (
  id, season, level, state_code, subdivision_id, name,
  start_date, end_date, venue, city, status
) values
  ('MI-D1-2027', '2026-27', 'district', 'MI', 'MI-D1', 'Michigan DECA District 1 Conference', '2026-12-10', '2026-12-10', 'Saginaw Valley State University', 'University Center', 'confirmed'),
  ('MI-D2-2027', '2026-27', 'district', 'MI', 'MI-D2', 'Michigan DECA District 2 Conference', null, null, null, null, 'tba'),
  ('MI-D3-2027', '2026-27', 'district', 'MI', 'MI-D3', 'Michigan DECA District 3 Conference', '2027-01-15', '2027-01-15', 'Western Michigan University', 'Kalamazoo', 'confirmed'),
  ('MI-D4-2027', '2026-27', 'district', 'MI', 'MI-D4', 'Michigan DECA District 4 Conference', '2027-01-06', '2027-01-06', 'Eastern Michigan University', 'Ypsilanti', 'confirmed'),
  ('MI-D5-2027', '2026-27', 'district', 'MI', 'MI-D5', 'Michigan DECA District 5 Conference', '2027-01-07', '2027-01-07', 'Eastern Michigan University', 'Ypsilanti', 'confirmed'),
  ('MI-D6-2027', '2026-27', 'district', 'MI', 'MI-D6', 'Michigan DECA District 6 Conference', null, null, null, null, 'tba'),
  ('MI-D7-2027', '2026-27', 'district', 'MI', 'MI-D7', 'Michigan DECA District 7 Conference', '2026-12-15', '2026-12-15', 'Macomb Community College', 'Warren', 'confirmed'),
  ('MI-D8-2027', '2026-27', 'district', 'MI', 'MI-D8', 'Michigan DECA District 8 Conference', '2026-12-16', '2026-12-16', 'Wayne County Community College Taylor Campus', 'Taylor', 'confirmed'),
  ('MI-D9-2027', '2026-27', 'district', 'MI', 'MI-D9', 'Michigan DECA District 9 Conference', '2027-01-08', '2027-01-08', 'Eastern Michigan University', 'Ypsilanti', 'confirmed')
on conflict (id) do update set
  season = excluded.season,
  level = excluded.level,
  state_code = excluded.state_code,
  subdivision_id = excluded.subdivision_id,
  name = excluded.name,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  venue = excluded.venue,
  city = excluded.city,
  status = excluded.status,
  updated_at = now();

create index if not exists idx_subdivisions_state_active
  on public.deca_subdivisions(state_code, is_active, number);
create index if not exists idx_conferences_state_season
  on public.deca_conferences(state_code, season, level);
create index if not exists idx_conferences_subdivision
  on public.deca_conferences(subdivision_id);
create index if not exists idx_profiles_location
  on public.profiles(state_code, deca_subdivision_id, subdivision_status);

alter table public.states enable row level security;
alter table public.deca_subdivisions enable row level security;
alter table public.deca_conferences enable row level security;

drop policy if exists states_read_active on public.states;
create policy states_read_active on public.states
  for select to authenticated using (is_active);

drop policy if exists states_deny_student_writes on public.states;
create policy states_deny_student_writes on public.states
  for all to authenticated using (false) with check (false);

drop policy if exists deca_subdivisions_read_active on public.deca_subdivisions;
create policy deca_subdivisions_read_active on public.deca_subdivisions
  for select to authenticated using (is_active);

drop policy if exists deca_subdivisions_deny_student_writes on public.deca_subdivisions;
create policy deca_subdivisions_deny_student_writes on public.deca_subdivisions
  for all to authenticated using (false) with check (false);

drop policy if exists deca_conferences_read_active on public.deca_conferences;
create policy deca_conferences_read_active on public.deca_conferences
  for select to authenticated using (status in ('confirmed', 'tba'));

drop policy if exists deca_conferences_deny_student_writes on public.deca_conferences;
create policy deca_conferences_deny_student_writes on public.deca_conferences
  for all to authenticated using (false) with check (false);

grant select on table public.states, public.deca_subdivisions, public.deca_conferences
  to authenticated;
