-- Applied to production as migration 20260816210032.
create table public.lesson_audit_batches (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'queued'
    check (status in ('queued', 'processing', 'complete', 'failed')),
  requested_count integer not null default 20 check (requested_count between 1 and 20),
  processed_count integer not null default 0 check (processed_count >= 0),
  failed_count integer not null default 0 check (failed_count >= 0),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz
);

create table public.lesson_content_audits (
  id uuid primary key default gen_random_uuid(),
  batch_id uuid not null references public.lesson_audit_batches(id) on delete cascade,
  kpi_id text not null references public.kpi_catalog(id) on delete cascade,
  complexity text not null check (complexity in ('quick', 'standard', 'deep')),
  skill_type text not null,
  generated_lesson jsonb,
  generation_status text not null default 'queued'
    check (generation_status in ('queued', 'processing', 'ready', 'failed')),
  failure_reason text,
  mission_clarity smallint check (mission_clarity between 1 and 5),
  choice_matters smallint check (choice_matters between 1 and 5),
  vocabulary_quality smallint check (vocabulary_quality between 1 and 5),
  learning_value smallint check (learning_value between 1 and 5),
  difficulty_progression smallint check (difficulty_progression between 1 and 5),
  pacing_quality smallint check (pacing_quality between 1 and 5),
  notes text,
  review_status text not null default 'pending'
    check (review_status in ('pending', 'passed', 'needs_revision', 'deferred')),
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (batch_id, kpi_id)
);

create table public.lesson_generation_failures (
  id bigint generated by default as identity primary key,
  kpi_id text not null,
  user_id uuid references auth.users(id) on delete set null,
  provider_summary text not null default '',
  created_at timestamptz not null default now()
);

create index idx_lesson_content_audits_review
  on public.lesson_content_audits (review_status, generation_status, created_at);
create index idx_lesson_generation_failures_kpi
  on public.lesson_generation_failures (kpi_id, created_at desc);

alter table public.lesson_audit_batches enable row level security;
alter table public.lesson_content_audits enable row level security;
alter table public.lesson_generation_failures enable row level security;

revoke all on table public.lesson_audit_batches from anon, authenticated;
revoke all on table public.lesson_content_audits from anon, authenticated;
revoke all on table public.lesson_generation_failures from anon, authenticated;

grant select, insert, update, delete on table public.lesson_audit_batches to service_role;
grant select, insert, update, delete on table public.lesson_content_audits to service_role;
grant select, insert, update, delete on table public.lesson_generation_failures to service_role;
grant usage, select on sequence public.lesson_generation_failures_id_seq to service_role;
